// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: neural_network.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_neural_5fnetwork_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_neural_5fnetwork_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_neural_5fnetwork_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_neural_5fnetwork_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_neural_5fnetwork_2eproto;
namespace s21 {
class MatrixMessage;
struct MatrixMessageDefaultTypeInternal;
extern MatrixMessageDefaultTypeInternal _MatrixMessage_default_instance_;
class NeuralNetworkMessage;
struct NeuralNetworkMessageDefaultTypeInternal;
extern NeuralNetworkMessageDefaultTypeInternal _NeuralNetworkMessage_default_instance_;
class Vector;
struct VectorDefaultTypeInternal;
extern VectorDefaultTypeInternal _Vector_default_instance_;
}  // namespace s21
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace s21 {

// ===================================================================


// -------------------------------------------------------------------

class NeuralNetworkMessage final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:s21.NeuralNetworkMessage) */ {
 public:
  inline NeuralNetworkMessage() : NeuralNetworkMessage(nullptr) {}
  ~NeuralNetworkMessage() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR NeuralNetworkMessage(::google::protobuf::internal::ConstantInitialized);

  NeuralNetworkMessage(const NeuralNetworkMessage& from);
  NeuralNetworkMessage(NeuralNetworkMessage&& from) noexcept
    : NeuralNetworkMessage() {
    *this = ::std::move(from);
  }

  inline NeuralNetworkMessage& operator=(const NeuralNetworkMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline NeuralNetworkMessage& operator=(NeuralNetworkMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NeuralNetworkMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const NeuralNetworkMessage* internal_default_instance() {
    return reinterpret_cast<const NeuralNetworkMessage*>(
               &_NeuralNetworkMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NeuralNetworkMessage& a, NeuralNetworkMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(NeuralNetworkMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NeuralNetworkMessage* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NeuralNetworkMessage* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NeuralNetworkMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NeuralNetworkMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const NeuralNetworkMessage& from) {
    NeuralNetworkMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NeuralNetworkMessage* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "s21.NeuralNetworkMessage";
  }
  protected:
  explicit NeuralNetworkMessage(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWeightsHiddenFieldNumber = 3,
    kBiasHiddenFieldNumber = 5,
    kWeightsOutputFieldNumber = 4,
    kBiasOutputFieldNumber = 6,
    kLearningRateFieldNumber = 1,
    kHiddenLayersCountFieldNumber = 2,
  };
  // repeated .s21.MatrixMessage weights_hidden_ = 3;
  int weights_hidden__size() const;
  private:
  int _internal_weights_hidden__size() const;

  public:
  void clear_weights_hidden_() ;
  ::s21::MatrixMessage* mutable_weights_hidden_(int index);
  ::google::protobuf::RepeatedPtrField< ::s21::MatrixMessage >*
      mutable_weights_hidden_();
  private:
  const ::google::protobuf::RepeatedPtrField<::s21::MatrixMessage>& _internal_weights_hidden_() const;
  ::google::protobuf::RepeatedPtrField<::s21::MatrixMessage>* _internal_mutable_weights_hidden_();
  public:
  const ::s21::MatrixMessage& weights_hidden_(int index) const;
  ::s21::MatrixMessage* add_weights_hidden_();
  const ::google::protobuf::RepeatedPtrField< ::s21::MatrixMessage >&
      weights_hidden_() const;
  // repeated .s21.MatrixMessage bias_hidden_ = 5;
  int bias_hidden__size() const;
  private:
  int _internal_bias_hidden__size() const;

  public:
  void clear_bias_hidden_() ;
  ::s21::MatrixMessage* mutable_bias_hidden_(int index);
  ::google::protobuf::RepeatedPtrField< ::s21::MatrixMessage >*
      mutable_bias_hidden_();
  private:
  const ::google::protobuf::RepeatedPtrField<::s21::MatrixMessage>& _internal_bias_hidden_() const;
  ::google::protobuf::RepeatedPtrField<::s21::MatrixMessage>* _internal_mutable_bias_hidden_();
  public:
  const ::s21::MatrixMessage& bias_hidden_(int index) const;
  ::s21::MatrixMessage* add_bias_hidden_();
  const ::google::protobuf::RepeatedPtrField< ::s21::MatrixMessage >&
      bias_hidden_() const;
  // .s21.MatrixMessage weights_output_ = 4;
  bool has_weights_output_() const;
  void clear_weights_output_() ;
  const ::s21::MatrixMessage& weights_output_() const;
  PROTOBUF_NODISCARD ::s21::MatrixMessage* release_weights_output_();
  ::s21::MatrixMessage* mutable_weights_output_();
  void set_allocated_weights_output_(::s21::MatrixMessage* value);
  void unsafe_arena_set_allocated_weights_output_(::s21::MatrixMessage* value);
  ::s21::MatrixMessage* unsafe_arena_release_weights_output_();

  private:
  const ::s21::MatrixMessage& _internal_weights_output_() const;
  ::s21::MatrixMessage* _internal_mutable_weights_output_();

  public:
  // .s21.MatrixMessage bias_output_ = 6;
  bool has_bias_output_() const;
  void clear_bias_output_() ;
  const ::s21::MatrixMessage& bias_output_() const;
  PROTOBUF_NODISCARD ::s21::MatrixMessage* release_bias_output_();
  ::s21::MatrixMessage* mutable_bias_output_();
  void set_allocated_bias_output_(::s21::MatrixMessage* value);
  void unsafe_arena_set_allocated_bias_output_(::s21::MatrixMessage* value);
  ::s21::MatrixMessage* unsafe_arena_release_bias_output_();

  private:
  const ::s21::MatrixMessage& _internal_bias_output_() const;
  ::s21::MatrixMessage* _internal_mutable_bias_output_();

  public:
  // double learning_rate = 1;
  void clear_learning_rate() ;
  double learning_rate() const;
  void set_learning_rate(double value);

  private:
  double _internal_learning_rate() const;
  void _internal_set_learning_rate(double value);

  public:
  // int32 hidden_layers_count_ = 2;
  void clear_hidden_layers_count_() ;
  ::int32_t hidden_layers_count_() const;
  void set_hidden_layers_count_(::int32_t value);

  private:
  ::int32_t _internal_hidden_layers_count_() const;
  void _internal_set_hidden_layers_count_(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:s21.NeuralNetworkMessage)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6, 4, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::s21::MatrixMessage > weights_hidden__;
    ::google::protobuf::RepeatedPtrField< ::s21::MatrixMessage > bias_hidden__;
    ::s21::MatrixMessage* weights_output__;
    ::s21::MatrixMessage* bias_output__;
    double learning_rate_;
    ::int32_t hidden_layers_count__;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_neural_5fnetwork_2eproto;
};// -------------------------------------------------------------------

class MatrixMessage final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:s21.MatrixMessage) */ {
 public:
  inline MatrixMessage() : MatrixMessage(nullptr) {}
  ~MatrixMessage() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR MatrixMessage(::google::protobuf::internal::ConstantInitialized);

  MatrixMessage(const MatrixMessage& from);
  MatrixMessage(MatrixMessage&& from) noexcept
    : MatrixMessage() {
    *this = ::std::move(from);
  }

  inline MatrixMessage& operator=(const MatrixMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline MatrixMessage& operator=(MatrixMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MatrixMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const MatrixMessage* internal_default_instance() {
    return reinterpret_cast<const MatrixMessage*>(
               &_MatrixMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MatrixMessage& a, MatrixMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(MatrixMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MatrixMessage* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MatrixMessage* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MatrixMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MatrixMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const MatrixMessage& from) {
    MatrixMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MatrixMessage* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "s21.MatrixMessage";
  }
  protected:
  explicit MatrixMessage(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
  };
  // repeated .s21.Vector data_ = 1;
  int data__size() const;
  private:
  int _internal_data__size() const;

  public:
  void clear_data_() ;
  ::s21::Vector* mutable_data_(int index);
  ::google::protobuf::RepeatedPtrField< ::s21::Vector >*
      mutable_data_();
  private:
  const ::google::protobuf::RepeatedPtrField<::s21::Vector>& _internal_data_() const;
  ::google::protobuf::RepeatedPtrField<::s21::Vector>* _internal_mutable_data_();
  public:
  const ::s21::Vector& data_(int index) const;
  ::s21::Vector* add_data_();
  const ::google::protobuf::RepeatedPtrField< ::s21::Vector >&
      data_() const;
  // @@protoc_insertion_point(class_scope:s21.MatrixMessage)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1, 1, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::RepeatedPtrField< ::s21::Vector > data__;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_neural_5fnetwork_2eproto;
};// -------------------------------------------------------------------

class Vector final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:s21.Vector) */ {
 public:
  inline Vector() : Vector(nullptr) {}
  ~Vector() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Vector(::google::protobuf::internal::ConstantInitialized);

  Vector(const Vector& from);
  Vector(Vector&& from) noexcept
    : Vector() {
    *this = ::std::move(from);
  }

  inline Vector& operator=(const Vector& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector& operator=(Vector&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vector& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vector* internal_default_instance() {
    return reinterpret_cast<const Vector*>(
               &_Vector_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Vector& a, Vector& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vector* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vector* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Vector>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Vector& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const Vector& from) {
    Vector::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "s21.Vector";
  }
  protected:
  explicit Vector(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
  };
  // repeated double data_ = 1;
  int data__size() const;
  private:
  int _internal_data__size() const;

  public:
  void clear_data_() ;
  double data_(int index) const;
  void set_data_(int index, double value);
  void add_data_(double value);
  const ::google::protobuf::RepeatedField<double>& data_() const;
  ::google::protobuf::RepeatedField<double>* mutable_data_();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_data_() const;
  ::google::protobuf::RepeatedField<double>* _internal_mutable_data_();

  public:
  // @@protoc_insertion_point(class_scope:s21.Vector)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::RepeatedField<double> data__;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_neural_5fnetwork_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// NeuralNetworkMessage

// double learning_rate = 1;
inline void NeuralNetworkMessage::clear_learning_rate() {
  _impl_.learning_rate_ = 0;
}
inline double NeuralNetworkMessage::learning_rate() const {
  // @@protoc_insertion_point(field_get:s21.NeuralNetworkMessage.learning_rate)
  return _internal_learning_rate();
}
inline void NeuralNetworkMessage::set_learning_rate(double value) {
  _internal_set_learning_rate(value);
  // @@protoc_insertion_point(field_set:s21.NeuralNetworkMessage.learning_rate)
}
inline double NeuralNetworkMessage::_internal_learning_rate() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.learning_rate_;
}
inline void NeuralNetworkMessage::_internal_set_learning_rate(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.learning_rate_ = value;
}

// int32 hidden_layers_count_ = 2;
inline void NeuralNetworkMessage::clear_hidden_layers_count_() {
  _impl_.hidden_layers_count__ = 0;
}
inline ::int32_t NeuralNetworkMessage::hidden_layers_count_() const {
  // @@protoc_insertion_point(field_get:s21.NeuralNetworkMessage.hidden_layers_count_)
  return _internal_hidden_layers_count_();
}
inline void NeuralNetworkMessage::set_hidden_layers_count_(::int32_t value) {
  _internal_set_hidden_layers_count_(value);
  // @@protoc_insertion_point(field_set:s21.NeuralNetworkMessage.hidden_layers_count_)
}
inline ::int32_t NeuralNetworkMessage::_internal_hidden_layers_count_() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.hidden_layers_count__;
}
inline void NeuralNetworkMessage::_internal_set_hidden_layers_count_(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.hidden_layers_count__ = value;
}

// repeated .s21.MatrixMessage weights_hidden_ = 3;
inline int NeuralNetworkMessage::_internal_weights_hidden__size() const {
  return _internal_weights_hidden_().size();
}
inline int NeuralNetworkMessage::weights_hidden__size() const {
  return _internal_weights_hidden__size();
}
inline void NeuralNetworkMessage::clear_weights_hidden_() {
  _internal_mutable_weights_hidden_()->Clear();
}
inline ::s21::MatrixMessage* NeuralNetworkMessage::mutable_weights_hidden_(int index) {
  // @@protoc_insertion_point(field_mutable:s21.NeuralNetworkMessage.weights_hidden_)
  return _internal_mutable_weights_hidden_()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::s21::MatrixMessage >*
NeuralNetworkMessage::mutable_weights_hidden_() {
  // @@protoc_insertion_point(field_mutable_list:s21.NeuralNetworkMessage.weights_hidden_)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_weights_hidden_();
}
inline const ::s21::MatrixMessage& NeuralNetworkMessage::weights_hidden_(int index) const {
  // @@protoc_insertion_point(field_get:s21.NeuralNetworkMessage.weights_hidden_)
    return _internal_weights_hidden_().Get(index);
}
inline ::s21::MatrixMessage* NeuralNetworkMessage::add_weights_hidden_() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::s21::MatrixMessage* _add = _internal_mutable_weights_hidden_()->Add();
  // @@protoc_insertion_point(field_add:s21.NeuralNetworkMessage.weights_hidden_)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField< ::s21::MatrixMessage >&
NeuralNetworkMessage::weights_hidden_() const {
  // @@protoc_insertion_point(field_list:s21.NeuralNetworkMessage.weights_hidden_)
  return _internal_weights_hidden_();
}
inline const ::google::protobuf::RepeatedPtrField<::s21::MatrixMessage>&
NeuralNetworkMessage::_internal_weights_hidden_() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.weights_hidden__;
}
inline ::google::protobuf::RepeatedPtrField<::s21::MatrixMessage>*
NeuralNetworkMessage::_internal_mutable_weights_hidden_() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.weights_hidden__;
}

// .s21.MatrixMessage weights_output_ = 4;
inline bool NeuralNetworkMessage::has_weights_output_() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.weights_output__ != nullptr);
  return value;
}
inline void NeuralNetworkMessage::clear_weights_output_() {
  if (_impl_.weights_output__ != nullptr) _impl_.weights_output__->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::s21::MatrixMessage& NeuralNetworkMessage::_internal_weights_output_() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::s21::MatrixMessage* p = _impl_.weights_output__;
  return p != nullptr ? *p : reinterpret_cast<const ::s21::MatrixMessage&>(::s21::_MatrixMessage_default_instance_);
}
inline const ::s21::MatrixMessage& NeuralNetworkMessage::weights_output_() const {
  // @@protoc_insertion_point(field_get:s21.NeuralNetworkMessage.weights_output_)
  return _internal_weights_output_();
}
inline void NeuralNetworkMessage::unsafe_arena_set_allocated_weights_output_(::s21::MatrixMessage* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.weights_output__);
  }
  _impl_.weights_output__ = reinterpret_cast<::s21::MatrixMessage*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:s21.NeuralNetworkMessage.weights_output_)
}
inline ::s21::MatrixMessage* NeuralNetworkMessage::release_weights_output_() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::s21::MatrixMessage* released = _impl_.weights_output__;
  _impl_.weights_output__ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::s21::MatrixMessage* NeuralNetworkMessage::unsafe_arena_release_weights_output_() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:s21.NeuralNetworkMessage.weights_output_)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::s21::MatrixMessage* temp = _impl_.weights_output__;
  _impl_.weights_output__ = nullptr;
  return temp;
}
inline ::s21::MatrixMessage* NeuralNetworkMessage::_internal_mutable_weights_output_() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.weights_output__ == nullptr) {
    auto* p = CreateMaybeMessage<::s21::MatrixMessage>(GetArenaForAllocation());
    _impl_.weights_output__ = reinterpret_cast<::s21::MatrixMessage*>(p);
  }
  return _impl_.weights_output__;
}
inline ::s21::MatrixMessage* NeuralNetworkMessage::mutable_weights_output_() {
  ::s21::MatrixMessage* _msg = _internal_mutable_weights_output_();
  // @@protoc_insertion_point(field_mutable:s21.NeuralNetworkMessage.weights_output_)
  return _msg;
}
inline void NeuralNetworkMessage::set_allocated_weights_output_(::s21::MatrixMessage* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::s21::MatrixMessage*>(_impl_.weights_output__);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::s21::MatrixMessage*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.weights_output__ = reinterpret_cast<::s21::MatrixMessage*>(value);
  // @@protoc_insertion_point(field_set_allocated:s21.NeuralNetworkMessage.weights_output_)
}

// repeated .s21.MatrixMessage bias_hidden_ = 5;
inline int NeuralNetworkMessage::_internal_bias_hidden__size() const {
  return _internal_bias_hidden_().size();
}
inline int NeuralNetworkMessage::bias_hidden__size() const {
  return _internal_bias_hidden__size();
}
inline void NeuralNetworkMessage::clear_bias_hidden_() {
  _internal_mutable_bias_hidden_()->Clear();
}
inline ::s21::MatrixMessage* NeuralNetworkMessage::mutable_bias_hidden_(int index) {
  // @@protoc_insertion_point(field_mutable:s21.NeuralNetworkMessage.bias_hidden_)
  return _internal_mutable_bias_hidden_()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::s21::MatrixMessage >*
NeuralNetworkMessage::mutable_bias_hidden_() {
  // @@protoc_insertion_point(field_mutable_list:s21.NeuralNetworkMessage.bias_hidden_)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_bias_hidden_();
}
inline const ::s21::MatrixMessage& NeuralNetworkMessage::bias_hidden_(int index) const {
  // @@protoc_insertion_point(field_get:s21.NeuralNetworkMessage.bias_hidden_)
    return _internal_bias_hidden_().Get(index);
}
inline ::s21::MatrixMessage* NeuralNetworkMessage::add_bias_hidden_() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::s21::MatrixMessage* _add = _internal_mutable_bias_hidden_()->Add();
  // @@protoc_insertion_point(field_add:s21.NeuralNetworkMessage.bias_hidden_)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField< ::s21::MatrixMessage >&
NeuralNetworkMessage::bias_hidden_() const {
  // @@protoc_insertion_point(field_list:s21.NeuralNetworkMessage.bias_hidden_)
  return _internal_bias_hidden_();
}
inline const ::google::protobuf::RepeatedPtrField<::s21::MatrixMessage>&
NeuralNetworkMessage::_internal_bias_hidden_() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.bias_hidden__;
}
inline ::google::protobuf::RepeatedPtrField<::s21::MatrixMessage>*
NeuralNetworkMessage::_internal_mutable_bias_hidden_() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.bias_hidden__;
}

// .s21.MatrixMessage bias_output_ = 6;
inline bool NeuralNetworkMessage::has_bias_output_() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.bias_output__ != nullptr);
  return value;
}
inline void NeuralNetworkMessage::clear_bias_output_() {
  if (_impl_.bias_output__ != nullptr) _impl_.bias_output__->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::s21::MatrixMessage& NeuralNetworkMessage::_internal_bias_output_() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::s21::MatrixMessage* p = _impl_.bias_output__;
  return p != nullptr ? *p : reinterpret_cast<const ::s21::MatrixMessage&>(::s21::_MatrixMessage_default_instance_);
}
inline const ::s21::MatrixMessage& NeuralNetworkMessage::bias_output_() const {
  // @@protoc_insertion_point(field_get:s21.NeuralNetworkMessage.bias_output_)
  return _internal_bias_output_();
}
inline void NeuralNetworkMessage::unsafe_arena_set_allocated_bias_output_(::s21::MatrixMessage* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.bias_output__);
  }
  _impl_.bias_output__ = reinterpret_cast<::s21::MatrixMessage*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:s21.NeuralNetworkMessage.bias_output_)
}
inline ::s21::MatrixMessage* NeuralNetworkMessage::release_bias_output_() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::s21::MatrixMessage* released = _impl_.bias_output__;
  _impl_.bias_output__ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::s21::MatrixMessage* NeuralNetworkMessage::unsafe_arena_release_bias_output_() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:s21.NeuralNetworkMessage.bias_output_)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::s21::MatrixMessage* temp = _impl_.bias_output__;
  _impl_.bias_output__ = nullptr;
  return temp;
}
inline ::s21::MatrixMessage* NeuralNetworkMessage::_internal_mutable_bias_output_() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.bias_output__ == nullptr) {
    auto* p = CreateMaybeMessage<::s21::MatrixMessage>(GetArenaForAllocation());
    _impl_.bias_output__ = reinterpret_cast<::s21::MatrixMessage*>(p);
  }
  return _impl_.bias_output__;
}
inline ::s21::MatrixMessage* NeuralNetworkMessage::mutable_bias_output_() {
  ::s21::MatrixMessage* _msg = _internal_mutable_bias_output_();
  // @@protoc_insertion_point(field_mutable:s21.NeuralNetworkMessage.bias_output_)
  return _msg;
}
inline void NeuralNetworkMessage::set_allocated_bias_output_(::s21::MatrixMessage* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::s21::MatrixMessage*>(_impl_.bias_output__);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::s21::MatrixMessage*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.bias_output__ = reinterpret_cast<::s21::MatrixMessage*>(value);
  // @@protoc_insertion_point(field_set_allocated:s21.NeuralNetworkMessage.bias_output_)
}

// -------------------------------------------------------------------

// MatrixMessage

// repeated .s21.Vector data_ = 1;
inline int MatrixMessage::_internal_data__size() const {
  return _internal_data_().size();
}
inline int MatrixMessage::data__size() const {
  return _internal_data__size();
}
inline void MatrixMessage::clear_data_() {
  _internal_mutable_data_()->Clear();
}
inline ::s21::Vector* MatrixMessage::mutable_data_(int index) {
  // @@protoc_insertion_point(field_mutable:s21.MatrixMessage.data_)
  return _internal_mutable_data_()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::s21::Vector >*
MatrixMessage::mutable_data_() {
  // @@protoc_insertion_point(field_mutable_list:s21.MatrixMessage.data_)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_data_();
}
inline const ::s21::Vector& MatrixMessage::data_(int index) const {
  // @@protoc_insertion_point(field_get:s21.MatrixMessage.data_)
    return _internal_data_().Get(index);
}
inline ::s21::Vector* MatrixMessage::add_data_() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::s21::Vector* _add = _internal_mutable_data_()->Add();
  // @@protoc_insertion_point(field_add:s21.MatrixMessage.data_)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField< ::s21::Vector >&
MatrixMessage::data_() const {
  // @@protoc_insertion_point(field_list:s21.MatrixMessage.data_)
  return _internal_data_();
}
inline const ::google::protobuf::RepeatedPtrField<::s21::Vector>&
MatrixMessage::_internal_data_() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.data__;
}
inline ::google::protobuf::RepeatedPtrField<::s21::Vector>*
MatrixMessage::_internal_mutable_data_() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.data__;
}

// -------------------------------------------------------------------

// Vector

// repeated double data_ = 1;
inline int Vector::_internal_data__size() const {
  return _internal_data_().size();
}
inline int Vector::data__size() const {
  return _internal_data__size();
}
inline void Vector::clear_data_() {
  _internal_mutable_data_()->Clear();
}
inline double Vector::data_(int index) const {
  // @@protoc_insertion_point(field_get:s21.Vector.data_)
  return _internal_data_().Get(index);
}
inline void Vector::set_data_(int index, double value) {
  _internal_mutable_data_()->Set(index, value);
  // @@protoc_insertion_point(field_set:s21.Vector.data_)
}
inline void Vector::add_data_(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_data_()->Add(value);
  // @@protoc_insertion_point(field_add:s21.Vector.data_)
}
inline const ::google::protobuf::RepeatedField<double>& Vector::data_() const {
  // @@protoc_insertion_point(field_list:s21.Vector.data_)
  return _internal_data_();
}
inline ::google::protobuf::RepeatedField<double>* Vector::mutable_data_() {
  // @@protoc_insertion_point(field_mutable_list:s21.Vector.data_)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_data_();
}

inline const ::google::protobuf::RepeatedField<double>& Vector::_internal_data_() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.data__;
}
inline ::google::protobuf::RepeatedField<double>* Vector::_internal_mutable_data_() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.data__;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace s21


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_neural_5fnetwork_2eproto_2epb_2eh
